f = open("data4_k=4.py","w")
f.write("n_d_k = " + repr(n_d_k) + "\n")
f.write("n_k_w = " + repr(n_k_w) + "\n")
f.write("n_k = " + repr(n_k) + "\n")
f.write("topic_per_word = " + repr(topic_per_word) + "\n")
f.write("vocabulary = " + repr(vocabulary) + "\n")
f.write("documents = " + repr(documents) + "\n")
f.write("alpha = " + repr(alpha) + "\n")
f.write("beta = " + repr(beta) + "\n")
f.write("k = " + repr(k) + "\n")
